window.PROJECTS = {
      'bootcamp': {
        num: '01', numColor: '#e81416',
        title: 'Agentic Data &amp; Analytics Bootcamp',
        category: 'Marketing &amp; Sales',
        tags: ['Demand Gen', 'Education', 'Partner Marketing', 'Microsoft Azure'],
        // heroImage moved into `screens` thumbnails (no dedicated hero image panel).
        heroCaption: 'Promotional banner: free two-day virtual Agentic Data & Analytics Bootcamp, with Ascend.io and Microsoft Azure sponsor lockup.',
        // heroFit removed (hero image panel no longer used).
        impact: { num: '5,000+', label: 'registrants across two cohorts' },
        links: [
          { label: 'data-and-ai-bootcamp.com', url: 'https://www.data-and-ai-bootcamp.com/' },
          { label: 'docs.ascend.io/bootcamp', url: 'https://docs.ascend.io/bootcamp/' },
        ],
        aiAssisted: true,
        aiDesc: [
          'The bootcamp was itself a live demonstration of what agentic AI can do for data teams — which made it feel right to use AI throughout the production process too.',
          'The first phase was content: drafting the curriculum, building out the lab guides in Docusaurus, and iterating on communications and campaigns. But the most interesting part was using agents to review the lab documentation itself — review agents that connected directly to Ascend\'s own agents via MCP servers, running the same prompts and steps we were asking participants to use. They tested the documentation from the inside. It let us catch problems, refine prompts, and ship cleaner labs without relying on a heavy human QA cycle.',
          'Post-event, I built a data pipeline using AI to analyze the registrant and participant data — identifying which cohort members to prioritize for follow-up and routing them into targeted outbound email sequences. The bootcamp produced a lot of signal. The pipeline made sure we acted on it.',
        ],
        body: [
          'Everyone was talking about AI. Fewer people could explain how to actually use it — safely, effectively, at scale. In the data space especially, there was a lot of noise and not much of a path. Data teams wanted to move but didn\'t know where to start. So we built one.',
          'The Agentic Data & Analytics Bootcamp was a <strong>free, two-day virtual program</strong> — multi-track, hands-on, with partner sessions from MotherDuck and Microsoft Azure. Participants didn\'t just learn about agentic data engineering. They built real data pipelines with AI agents before they left.',
          { kicker: 'What I owned', bullets: [
            'Curriculum architecture and lab guides in Docusaurus',
            'Speaker logistics and registrant campaigns',
            'Post-event follow-up: credentials, hackathon scoring, and email sequences',
          ]},
          'Across two cohorts, the event drew over 5,000 registrants, well above industry benchmarks for participation rates. Over 200 LinkedIn posts followed, from participants eagerly sharing about the things they\'d built and learned — from folks who were genuinely proud of what they\'d made. That doesn\'t happen by accident. It happens when an experience gives people something worth talking about.',
          'When we started, we didn\'t have a playbook to copy from. We figured a lot out in real time. But it was such an impactful experience. I\'d do it again. <strong>(And I did.)</strong>',
          { kicker: 'What participants said', bullets: [
            '"Big takeaway for me: agentic AI is less about clever prompts and more about thoughtful system design. With the right context, tools, triggers, and guardrails, agents become safe and useful."',
            '"In just a few hours, we built a complete carbon data pipeline and live analytics dashboard — something that traditionally would take days or weeks. We are entering a phase where data systems are no longer just pipelines — they are becoming autonomous collaborators."',
            '"This experience really highlighted how agentic workflows can reduce manual effort, improve reliability, and make analytics far more operational and scalable."',
            '"Huge thanks to the team for the expert guidance and a flawless event!"',
          ]},
        ],
        screens: [
          { label: 'Bootcamp promo banner', gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)', img: 'final-images/bootcamp-promo-banner.png', caption: 'Promotional banner: free two-day virtual Agentic Data &amp; Analytics Bootcamp, with Ascend.io and Microsoft Azure sponsor lockup.' },
          { label: 'Live virtual bootcamp', gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)', img: 'final-images/bootcamp-live-lab-session.png', caption: 'Live session in the webinar stack: deck, presenter feed, and attendee chat during the Agentic Data & Analytics Bootcamp.' },
          { label: 'Curriculum & lab hub', gradient: 'linear-gradient(135deg, #0f3460 0%, #533483 60%, #e94560 100%)', img: 'final-images/bootcamp-docs.png', caption: 'Participant-facing bootcamp home in Docusaurus — day structure, lab cards, and navigation for docs.ascend.io/bootcamp.' },
          { label: 'Bootcamp agenda sample', gradient: 'linear-gradient(135deg, #0f3460 0%, #533483 60%, #e94560 100%)', img: 'final-images/bootcamp-agenda-sample.png', caption: 'Example agenda layout used to structure the two-day bootcamp experience.' },
          { label: 'Bootcamp slides', gradient: 'linear-gradient(135deg, #0f3460 0%, #533483 60%, #e94560 100%)', img: 'final-images/bootcamp-slides.png', caption: 'Slide deck overview for the Agentic Data &amp; Analytics Bootcamp sessions.' },
          { label: 'Bootcamp speakers', gradient: 'linear-gradient(135deg, #0f3460 0%, #533483 60%, #e94560 100%)', img: 'final-images/bootcamp-speakers.png', caption: 'Speaker lineup and session presence for the bootcamp.' },
        ],
        overlayStyle: 'scale',
      },
      'website': {
        num: '02', numColor: '#ffa500',
        title: 'Ascend Website Redesign',
        category: 'Brand &amp; Marketing',
        tags: ['Brand', 'Messaging', 'Conversion', 'Category Creation'],
        impact: { num: '5×', label: 'conversions two weeks after launch' },
        aiAssisted: true,
        aiDesc: [
          'This project happened in early 2024, before agents were a reliable part of the workflow. What existed were powerful language models — capable, but only as focused as the context you gave them. So I treated the AI setup as an architecture problem.',
          'I built a dedicated ChatGPT project for the site with clear guidelines, rules, and a positioning framework baked in from the start. Each major section of the site got its own dedicated thread — not just for organization, but as a form of context engineering: keeping the model\'s working memory focused on one part of the story at a time rather than letting it drift. The rules I set up weren\'t just style preferences. They were the beginnings of an agentic harness — the same kind of structured AI guidance that would later become much more explicit in our agentic work.',
          'What that setup made possible was a fundamentally different pace of work. What would have taken weeks of document drafts happened in days — not because the AI was doing the thinking, but because it could hold context and push back on positioning in a way that made the thinking sharper and faster. I wasn\'t generating copy and editing it. I was working through the hardest positioning questions out loud with something that could actually respond.',
          'Otto\'s redesign was a separate AI adventure entirely — Nano Banana, a lot of image generations, and one moment where I genuinely thought: that\'s him.',
        ],
        body: [
          'We had spent a year rebuilding Ascend into an AI-native data engineering platform. The product had fundamentally changed, but the website hadn\'t kept up. It wasn\'t converting, it wasn\'t telling the right story, and we were about to launch a new category: <strong>Agentic Data Engineering</strong>. We needed a new language to help users and prospects understand the things we had built and the power they could harness from AI, and so we decided not to just refresh the website but rebuild everything.',
          { kicker: 'What I owned', bullets: [
            'Product marketing and positioning framework for a new category',
            'Audience mapping across eight buyer personas',
            'Content architecture and page-by-page copy across 40+ new designs',
          ]},
          'The build happened in six weeks with the team at FruitBowl Digital — they built all our new pages and migrated eight years of WordPress content. It was a massive undertaking under a tight timeline, and to watch everyone on the team rise to the occasion was genuinely inspiring.',
          'Alongside the site, we gave Otto a proper glow-up. He started as a Slack emoji someone generated at a conference table in Vegas three years ago. After about two hours and $15 on Nano Banana, he became the 3D character you see across the platform today. Friendly, curious, a little scrappy — which is pretty on-brand for how a lot of the best things at Ascend got made.',
        ],
        screens: [
          { label: 'Homepage — Hero & Positioning', gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', img: 'final-images/website-homepage.png', caption: 'Redesigned homepage hero and category positioning after the Agentic Data Engineering launch.' },
          { label: 'Product & Use Case Pages', gradient: 'linear-gradient(135deg, #764ba2 0%, #f093fb 50%, #f5576c 100%)', img: 'final-images/website-content2.png', caption: 'Product storytelling and use-case architecture from the same site program.' },
          { label: 'Website content', gradient: 'linear-gradient(135deg, #764ba2 0%, #f093fb 50%, #f5576c 100%)', img: 'final-images/website-content.png', caption: 'Expanded site content layout and structured messaging across sections.' },
          { label: 'Website social proof', gradient: 'linear-gradient(135deg, #764ba2 0%, #f093fb 50%, #f5576c 100%)', img: 'final-images/website-social-proof.png', caption: 'Social proof section presentation used to reinforce customer and community impact.' },
          { label: 'Website information architecture in Miro', gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', img: 'final-images/website-information-architecture-in-miro.png', caption: 'Information architecture mapping created in Miro for the redesigned website.' },
          { label: 'Website design phase in Figma', gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', img: 'final-images/website-design-phase-in-figma.png', caption: 'Design phase artifacts created in Figma during the website redesign.' },
        ],
        overlayStyle: 'scale',
      },
      'onboarding': {
        num: '03', numColor: '#79c314',
        title: 'Onboarding Program',
        category: 'People &amp; Ops',
        tags: ['Employee Experience', 'Operations', 'Retention'],
        impact: { num: '96%', label: 'of new hires felt more effective from day one' },
        aiAssisted: true,
        aiDesc: [
          'The most recent version of this program — a 40+ page onboarding guide I built for Dru, our Fractional VP of Marketing — was built almost entirely with AI assistance. I used Claude to help structure the guide, draft role-specific sections, and keep the voice consistent across a document that long. AI is genuinely good at holding, crafting, and disseminating massive amounts of context at once. Giving agents access to internal docs, a new hire\'s background, what they need to know in week one, produces tailored, high quality resources to empower folks to start making an impact right away.',
          'But the best part of leveraging these new AI skills to onboard Dru? He used AI to turn the onboarding doc into a podcast — and listened to it on his commute into the office on day one. By the time we sat down for our first meeting, he\'d already absorbed the whole thing. That\'s the version of onboarding I was trying to build.',
        ],
        body: [
          'When I started at Ascend, my first real project was formalizing our onboarding program. My own onboarding had been ad hoc — meetings with my hiring manager, a lot of questions, figuring it out as I went. The reality was that most new hires were getting different levels of support depending on their role. There wasn\'t a formalized structure in place to ensure people could hit the ground running with clear expectations and all the tools and resources they needed.',
          { kicker: 'What we put in place', bullets: [
            'Pre–day-one communication so people felt like insiders before they logged in',
            'A structured first week and role-specific ramp paths',
            'Buddy pairing and 30 / 60 / 90 check-ins to catch what was slipping',
          ]},
          'The design principle was simple: by the end of week one, someone should feel like they belong here and know what they\'re supposed to be doing. That sounds obvious but it\'s actually pretty hard to pull off consistently across different roles, levels, and time zones. The program had to scale without losing the personal quality that makes early days feel meaningful.',
          'Building out tracking systems, new hire checklists, and a consistent onboarding program resulted in 96% of new hires reporting they felt effective in their role from day one. It enabled new teammates to start shipping code and taking on-call shifts faster than they had before — and more importantly, it gave people a real foundation to success long-term.',
          { kicker: 'What new hires said', bullets: [
            '"I like that the process includes training on different areas of the company that may not directly relate to what I do — it helps build context and an overall process understanding."',
            '"[I appreciated] the onboarding docs tailored to my role with well documented things to do. I also enjoyed the clear team overview."',
            '"People are incredibly smart and helpful here — huge fan of the AMA [Ask me Anything] session as a forum to learn more about the company, technology, and team."',
          ]},
        ],
        screens: [
          { label: 'New Hire Welcome Kit', gradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)', img: 'final-images/onboarding-swag.png', caption: 'New-hire welcome swag box and note sent as part of the onboarding experience.' },
          { label: '30/60/90 Ramp Framework', gradient: 'linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)', img: 'final-images/onboarding-checklist-in-Monday.com.png', caption: '30/60/90 ramp checklist view used to structure role-specific onboarding progress.' },
        ],
        overlayStyle: 'scale',
      },
      'certification': {
        num: '04', numColor: '#487de7',
        title: 'Agentic DE Certification — 101, 201 &amp; 301',
        category: 'Education',
        tags: ['Curriculum', 'Credentialing', 'Category Creation', 'Community'],
        impact: { num: '21', label: 'modules across three courses · 48-hour build' },
        aiAssisted: true,
        aiDesc: [
          'Working with agents to build this in 48 hours was genuinely one of the most exciting things I\'ve done. The whole thing started in Cursor\'s planning mode — which is less like prompting and more like writing a spec. Before a single agent ran, I worked through a thorough implementation plan that defined the architecture, prompts for each subagent, the module outline and curriculum structure, rules and guidelines for what production-ready content actually meant in this context, and how we would grant certifications to folks who completed the courses.',
          'Having a clear, specific spec before we built meant we weren\'t figuring out the architecture mid-run. The agents had what they needed from the start. That\'s what made 48 hours possible — not speed for its own sake, but the kind of upfront clarity that let everything downstream move fast and stay coherent.',
        ],
        body: [
          'The knowledge existed. For two years, Ascend had led the bleeding edge of experimenting and exploring, pushing the boundaries on what data teams could do to leverage AI. We\'d published our findings: blog posts on agent architecture, lab guides on context engineering, deep dives into observability and governance. Each piece came from the real work we were doing with our own data workflows and the vision of helping data teams become more agentic.',
          'The problem was that none of it was connected. A data engineer trying to go from \'I get what agents are\' to \'I can run them reliably in production\' had to collect the pieces themselves and figure out the order. The curriculum wasn\'t there. Then our internal hackathon gave us 48 hours and a deadline.',
          'The approach I took was, in hindsight, the only right one: use the same kind of agentic system the curriculum teaches to build the curriculum itself. Here\'s how it worked:',
          { kicker: 'The architecture', bullets: [
            'Research subagents worked in parallel — one per module — pulling from two years of our published blog posts, labs, and documentation to build source-verified briefs before a single word of new content was written',
            'Writer subagents consumed those briefs and produced full, comprehensive modules',
            'Eight parallel reviewer subagents ran simultaneously against each draft, each with a distinct persona: a senior data engineer, an instructional designer, a legal reviewer, and five more — none of them talking to each other',
            'A synthesis subagent read all eight reports, deduplicated findings, issued a ranked change list, and rendered a verdict: needs revision or ready for human review',
            'Rerun the cycle until the synthesis subagent had no major issues to report. The synthesis subagent owned the readiness decision, not me. That constraint mattered — it meant I didn\'t need to review the content until it had been thoroughly checked against the highest standards for veracity, readability, and efficacy.',
          ]},
          'The result: 21 modules across three courses — 101 for foundations, 201 for systems design, 301 for production operations — each put through multiple rounds of parallel expert review, in the same 48-hour window that would have produced maybe three or four decent drafts by hand. What surprised me wasn\'t the speed. It was how the review structure changed the content. Eight independent reviewers with no shared context don\'t just catch errors — they surface tensions. The modules that went through the most revision rounds are consistently the strongest. The process didn\'t save us from hard thinking. It organized and accelerated it.',
        ],
        screens: [
          { label: '101 Foundations Track — Introduction', gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', img: 'final-images/certification-101-introduction.png', caption: '101 Foundations Track introduction screen inside the certification experience.' },
          { label: '101 Foundations Track — Maturity Assessment', gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', img: 'final-images/certification-ai-maturity-assessment.png', caption: 'ADE Learning Path maturity assessment inside the certification experience.' },
          { label: 'Certification Modules Overview', gradient: 'linear-gradient(135deg, #0099f7 0%, #4facfe 50%, #00f2fe 100%)', img: 'final-images/certification-modules.png', caption: 'Module selection and overview across the certification track.' },
          { label: '301 Advanced Practitioner Track — Module Quiz', gradient: 'linear-gradient(135deg, #0099f7 0%, #4facfe 50%, #00f2fe 100%)', img: 'final-images/certification-module-quiz.png', caption: 'Quiz and assessment interface used to validate mastery for the advanced track.' },
        ],
        overlayStyle: 'scale',
      },
      'values': {
        num: '05', numColor: '#70369d',
        title: 'Core Value Formation',
        category: 'Culture',
        tags: ['Culture', 'Org Design', 'Facilitation', 'Leadership'],
        impact: { num: 'Company-wide', label: 'values that held up in real decisions' },
        aiAssisted: true,
        aiDesc: [
          'I used AI at two distinct points in this project. The first was in redesigning the recognition program — using it to generate ideas across a wide range, challenge the assumptions baked into the existing model, and map specific recognition formats to each of our four values. That ideation phase would have taken multiple team workshops; with AI it happened in a few focused sessions.',
          'The second was in producing the in-person rollout: agenda design, activity instructions, the value-themed scavenger hunt riddles for California Avenue. AI wrote the first drafts of everything and I refined them. The human work was in knowing which ideas would actually land with our team and which would feel forced. I find collaborating with agents to execute creative and delightful ideas enables me to deliver experiences that are far more powerful than I could deliver without these tools at hand.',
        ],
        body: [
          'We had core values at Ascend — but some of them had started to feel stale. They weren\'t guiding day-to-day decisions the way we needed them to. At the same time, we kept finding ourselves repeating two phrases that weren\'t formally part of our values yet but clearly needed to be: <em>Spark Delight</em> and <em>Consistently Curious</em>.',
          'The reasoning was clear. As we built a brand new platform, it became critical to orient the entire team — product, engineering, customer-facing — around building delightful experiences for our users. Delight wasn\'t a nice-to-have; it was a strategic direction. And as we pushed into agentic systems and the leading edge of AI, staying consistently curious wasn\'t optional. Without it, we knew we\'d fall behind.',
          'So we took a step back and restructured our core values to include both — and used that moment to revamp the recognition program around all four values: <em>I Got It, 1 Team 1 Dream, Spark Delight,</em> and <em>Consistently Curious.</em>',
          'The redesign moved us toward a continuous recognition model with real-time callouts, value-specific award formats, and more intentional rewards. We also ran an in-person rollout for the team: a scavenger hunt through California Avenue with value-themed riddles, a LEGO bridge-building challenge for \'I Got It,\' micro-research sprints for \'Consistently Curious,\' and a proper quarterly awards ceremony to tie it all together.',
          'Engagement skyrocketed. Belief in what the team could accomplish increased. Morale improved. The bar I always use for values work: do they change anything? Does someone make a different hiring decision, give harder feedback, hold a tougher line — because of the values? Ours passed that test. They showed up in performance reviews, in how we talked about hard decisions, and in what we celebrated. That\'s what made the program worth doing.',
        ],
        screens: [
          { label: 'Core Values', gradient: 'linear-gradient(135deg, #c471f5 0%, #fa71cd 100%)', img: 'final-images/core-values.png', caption: 'Core values definition and rollout foundation for the organization.' },
          { label: 'Core Values Rollout Slides', gradient: 'linear-gradient(135deg, #c471f5 0%, #fa71cd 100%)', img: 'final-images/core-values-rollout-slides.png', caption: 'In-person rollout materials used to reinforce the core value system.' },
        ],
        overlayStyle: 'scale',
      },
      'aisdr': {
        num: '06', numColor: '#4b369d',
        title: 'AI SDR Outreach Motion',
        category: 'Revenue',
        tags: ['Revenue', 'Pipeline', 'AI', 'GTM', 'AmpleMarket', 'Outbound'],
        impact: { num: 'Signal-based', label: 'targeting at scale — pipeline without added headcount' },
        aiAssisted: false,
        body: [
          'Getting outbound right is mostly a story of iteration. I tested a lot — AI SDR tools like Artisan, HubSpot\'s outbound agent, and others — before landing on AmpleMarket as our primary platform. AmpleMarket gave us a highly customizable agentic framework where we could leverage our own agentic expertise to tune messaging and craft more effective outbound than any other tool allowed.',
          'One of the earliest and most important things we learned: micro campaigns outperform broad ones. Hyper-targeted lists of 20–50 people, built around a specific signal or moment, consistently outperformed larger blasts. It forced better messaging — you can\'t be generic when your list is that focused — and it showed up in the results.',
          'The signal layer is the part most teams underinvest in. It\'s the difference between outbound that feels like research and outbound that feels like spam. We built the ICP criteria, the signal logic, and the message architecture around that principle — and kept tuning based on what was getting replies versus getting ignored.',
          'Other learnings: micro-campaigns of 20–50 people beat big blasts; the signal layer separated research from spam; LinkedIn outreach was far more effective than any other channel.',
        ],
        screens: [
          { label: 'Signal Targeting & Sequence Architecture', gradient: 'linear-gradient(135deg, #2c3e50 0%, #3498db 100%)', img: 'final-images/AI-SDR-custom instructions.png', caption: 'Custom instruction setup used to guide the AI SDR motion.' },
          { label: 'Personalization & Message Testing', gradient: 'linear-gradient(135deg, #3498db 0%, #2ecc71 100%)', img: 'final-images/AI-SDR-signal-based-outreach.png', caption: 'Signal-based outreach flow used to drive targeted sequencing and personalization.' },
        ],
        overlayStyle: 'scale',
      },
      'offsites': {
        num: '07', numColor: '#e6d000',
        title: 'Offsites, Hackathons &amp; Team Events',
        category: 'People',
        tags: ['Culture', 'Employee Experience', 'Remote', 'Engagement'],
        impact: { num: '50%', label: 'improvement in eNPS across program tenure' },
        aiAssisted: true,
        aiDesc: [
          'Event production has a lot of surface area. I use AI to draft and iterate on vendor research, logistics documentation, agenda design, internal communications, activity instructions, slide deck prep and review, and more.',
          'Collaborating with AI and agents where I can enables me to focus on the things that are more impactful — the judgment calls that it doesn\'t have the full sensibility to understand: what activities would fit the team\'s energy, how to structure a dinner for a group that hasn\'t been in a room together in six months, what the arc of the experience should feel like. Agentic workflows give me the space to be more intentional about these decisions that deeply impact the experience for everyone involved.',
        ],
        body: [
          'I\'ve run a lot of events in my career, and the thing I\'ve learned is that the success of an offsite is almost entirely determined by decisions that feel small — the dinner format on night one, how much unstructured time you leave, whether there\'s a space to gather after hours and play board games or a round of liar\'s dice (an Ascend team favorite). The big agenda items matter, but the experience people remember is usually in between them.',
          'The best offsites aren\'t just agendas; they\'re journeys. I think carefully about how to lead people through an experience that builds on itself, finding the perfect moments for alignment and focus, creative collaboration, and genuine connection. For a distributed team, in-person time is the opportunity to shape how people experience the team and the vision — to create the shared reference points that change how everyone works together for the rest of the year.',
          { kicker: 'What the program looked like', bullets: [
            'Quarterly in-person kickoffs to align the team around strategy and priorities',
            'Quarterly themed Hackdays (our most recent, "Agents Assemble," was an Avengers-themed event with a level of commitment to the bit that I stand by)',
            'Monthly team retrospectives — a time for folks to ask questions about anything across the business, from the roadmap to customer satisfaction',
            'Weekly all-hands and Demo Days where the team could show off their work and get recognized',
          ]},
          'Within my first six months at Ascend, we saw a 50% improvement in eNPS. I\'d be the first to say that\'s not entirely attributable to events — a lot of things go into whether people feel good about where they work. But building out these programs has been one of the most rewarding parts of my time at Ascend, and I\'ve loved continuing to invest in them.',
        ],
        screens: [
          { label: 'Company All-Hands & Offsites', gradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)', img: 'final-images/team-event-offsite-in-San-Diego.png', caption: 'In-person company offsite — the kind of all-hands and retreat programming this case study describes.' },
          { label: 'Team Volunteering', gradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)', img: 'final-images/team-events-volunteering.png', caption: 'Team volunteering session used to reinforce culture and shared purpose.' },
          { label: 'Hackathon & Team Sprints (AI in Wonderland)', gradient: 'linear-gradient(135deg, #ffd200 0%, #f7971e 50%, #f953c6 100%)', img: 'final-images/team-events-hackathon-AI-in-Wonderland-Theme.png', caption: 'Hackathon theme artwork representing an AI in Wonderland event format.' },
          { label: 'Hackathon & Team Sprints (Agents Assemble)', gradient: 'linear-gradient(135deg, #ffd200 0%, #f7971e 50%, #f953c6 100%)', img: 'final-images/team-events-hackathon-agentic-assemble-avengers-themed.png', caption: 'Internal hackday / team sprint energy — aligned with Ascend Hackdays like “Agents Assemble.”' },
        ],
        overlayStyle: 'scale',
      },
      'builtin': {
        num: '08', numColor: '#e81416',
        title: 'Built In Best Places to Work',
        category: 'Culture',
        tags: ['Recognition', 'Awards', 'Culture', 'Employee Experience'],
        impact: { num: '4 years', label: 'consecutive — the award follows the work' },
        aiAssisted: false,
        body: [
          'Building an award-winning culture requires a lot of intentionality. Winning four consecutive Built In Best Places to Work awards was less about the award and more about creating a space for everyone on the team to thrive.',
          'The Built In award is based on compensation, benefits, and the programs a company has in place to support its people. You can\'t manufacture it — if the underlying programs aren\'t there, the score reflects that. I owned the submission process each year, which meant telling the story of what we\'d actually built clearly and accurately. But the harder work was always the underlying programs themselves: onboarding, offsites, recognition, benefits design, the culture work. The award is downstream of all of that.',
          'Four years is a long time to sustain something in a startup environment where everything else is changing constantly. Headcount fluctuated, the product evolved, the market shifted. What stayed consistent was a genuine commitment to the people side of the company. The award was nice. The part that mattered was what it confirmed.',
        ],
        screens: [
          { label: 'Award Campaigns & Press', gradient: 'linear-gradient(135deg, #ff416c 0%, #ff4b2b 100%)', img: 'final-images/best-places-to-work-award.png', caption: 'Built In Best Places to Work listing — matches the external recognition this case study references.' },
          { label: 'Employee Survey Results', gradient: 'linear-gradient(135deg, #ff4b2b 0%, #f7971e 100%)', img: 'final-images/best-places-to-work-2025-blog-post.png', caption: 'Built In 2025 announcement content reflecting the survey-backed recognition.' },
        ],
        overlayStyle: 'scale',
      },
      'field-events': {
        num: '09', numColor: '#79c314',
        title: 'Field Events &amp; Webinar Program',
        category: 'Demand Gen',
        tags: ['Events', 'Co-Marketing', 'Pipeline', 'Webinars', 'Sequel.io', 'Snowflake', 'Databricks'],
        impact: { num: 'Pipeline', label: 'from conferences, webinars, and follow-up' },
        aiAssisted: true,
        aiDesc: [
          'AI is present throughout the entire events program — from planning to execution to follow-up. At the planning stage, I use AI agents to draft content calendars, build out event decks, and develop hands-on lab guides. During execution, AI helps me move faster on the things that need to happen at volume: recapping sessions, turning transcripts into blog posts, drafting persona-segmented follow-up sequences. After each event, I use AI to identify the highest quality opportunities in our lead data and personalize outbound to those folks at something closer to live speed.',
          'AI gives me the ability to effectively harvest the work we put into these programs. The event generates signal. AI helps make sure we actually act on it.',
        ],
        body: [
          'If you\'ve ever joined an Ascend webinar, attended a meetup, or visited our booth at a conference, we\'ve probably crossed paths! I\'ve owned Ascend\'s field events program end to end — from in-person conferences to a virtual webinar program I built from the ground up, across both owned and partner channels.',
          { kicker: 'What the program covered', bullets: [
            'In-person conference presence with teams of up to 20 people',
            'Pre-event training and messaging prep so the team could show up ready to have real conversations...not just hand out swag (iykyk)',
            'Diligent follow-up motion on the return to turn booth interactions into actual pipeline',
            'A virtual webinar program running up to 20 events a year across owned and partner channels',
          ]},
          'The webinar program became one of our most consistent drivers of pipeline and thought leadership. But the operational burden of running it manually was genuinely overwhelming at that volume. Moving to Sequel.io changed everything — setup went from days to hours, which let us run more events, respond faster to what the market was asking about, and give the program a real home on the Ascend website. The program compounded: each session became a blog post, a follow-up sequence, a series entry.',
          'The result was thousands of marketing qualified leads a year and a brand presence that showed up consistently wherever our customers were.',
        ],
        screens: [
          { label: 'Field Events — Snowflake World Tour Booth', gradient: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', img: 'final-images/field-events-snowflake-world-tour-booth.png', caption: 'Conference / field presence and partner co-marketing footprint from the events program.' },
          { label: 'Field Events — Snowflake Summit Booth', gradient: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', img: 'final-images/field-events-snowflake-summit-booth.png', caption: 'Booth presence supporting partner co-marketing and field engagement at Snowflake Summit.' },
          { label: 'Field Events — Sequel.io Event Hub', gradient: 'linear-gradient(135deg, #38f9d7 0%, #4facfe 100%)', img: 'final-images/field-events-sequel.io-event-hub.png', caption: 'Sequel.io-powered event hub entry point on the site for webinar content and follow-up.' },
          { label: 'Field Events — Sequel.io Dashboard', gradient: 'linear-gradient(135deg, #38f9d7 0%, #4facfe 100%)', img: 'final-images/field-events-sequel.io-dashboard.png', caption: 'Operational dashboard view used for event execution and follow-up motion.' },
          { label: 'Field Events — Hands-on Lab Build', gradient: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', img: 'final-images/field-events-Hands on Lab- Build API  Intesgtion Pipelines with AI.png', caption: 'Hands-on lab guide: Build API integration pipelines with AI.' },
          { label: 'Field Events — AWS Webinar Promo', gradient: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', img: 'final-images/Field-Events-Agentic Data Engineering on AWS Webinar Promo.png', caption: 'Promotional artwork for the Agentic Data Engineering on AWS webinar campaign.' },
        ],
        overlayStyle: 'scale',
      },
      'pricing': {
        num: '10', numColor: '#487de7',
        title: 'Plans &amp; Pricing Rollouts',
        category: 'GTM &amp; Strategy',
        tags: ['Pricing', 'GTM', 'Platform', 'Free trial', 'Launch', 'Sales Enablement'],
        impact: { num: 'Zero-noise', label: 'launches — tiers, trial & every function aligned' },
        aiAssisted: true,
        aiDesc: [
          'One of my favorite parts of leveraging AI for this project was building out pricing calculators for customers — interactive applications they could use to better understand how their usage would impact their pricing. With AI, generating these kinds of code-based applications becomes really easy, especially when we have a model in a spreadsheet that we can share with the LLM to generate those artifacts. It also builds a lot of trust and delight for customers to have a tailored pricing calculator that\'s bespoke to their needs and patterns.',
        ],
        body: [
          'Launching a new platform means launching new pricing from scratch — and doing it in a way that\'s fair to existing customers, reflects the actual cost of new capabilities like AI, and makes sense for a product that didn\'t exist in quite this form before. I partnered with leadership, product, and engineering to work through the models and tiers, iterating as the platform developed and making sure nothing we built created surprises for customers who\'d been with us before the transition.',
          'The launch of our free trial added another layer of complexity. A 14-day free trial for developers sounds simple, but it requires real clarity on conversion rate assumptions, infrastructure cost coverage, and what \'free\' actually costs the business before it becomes a customer. We needed numbers we could stand behind — not just pricing that felt right, but pricing that held up when you ran it through the spreadsheet.',
          'The hardest part of pricing work is that it touches everything simultaneously: product, sales, finance, customer success, and the customers themselves. My job was to hold all of those threads coherent — making sure the tiers made sense, the messaging was consistent across every function, and the launch landed without confusion or noise. Pricing changes that go well are invisible. That\'s the goal.',
        ],
        screens: [
          { label: 'Platform Tiers, Models & Migration', gradient: 'linear-gradient(135deg, #3a7bd5 0%, #3a6073 100%)', img: 'final-images/pricing.png', caption: 'Ascend pricing layout showing Explorer, Adventurer, and Standard tiers during the pricing rollout.', placeholder: false },
          { label: 'Free Trial, Finance & Launch Comms', gradient: 'linear-gradient(135deg, #3a6073 0%, #1a1a2e 100%)', img: 'final-images/pricing-interactive-calculator.png', caption: 'Interactive pricing calculator used to align trial, finance, and launch messaging.' },
        ],
        overlayStyle: 'scale',
      },
    };
